name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34fe6a60232970c455a4537d053e512c7a4eb25f2d603d62f03055f0321cb0cf"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
