name = "Vaulthalla"
author = "AlitaTeal"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e77dbccf6fc9d06034f72964d4c6fc30e932256d5370be62fc2a4697f060d62"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
