name = "Vaulthalla"
author = "AlitaTeal"
version = "9.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bde9f2e65799a4e04fd26d3f1c91115773e3181ed8cbedfe7b68fc21545c570"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
