name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ce0751b336940b46313b67be5ae2eb28fd2dc0d407b2ec0e262728d2785c2d0"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
