name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d60f8f1502af2afdd7f62aa23dd7e93053721ed25636d9a075e66befffa5d4e6"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
