name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2882b81eeab472d5da20329dc346554c4fe4754c6dfaeef2be8f7948728b104d"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
