name = "Vaulthalla"
author = "AlitaTeal"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75ff33573fa151d7661694d687a8e547b3277581e7e094f7e4253e4082e0cffb"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
