name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3f35c5dd5d0258b78895b35a444e5bffe21bb431137e136005ff6ec7199d979"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
