name = "Vaulthalla"
author = "AlitaTeal"
version = "9.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "171c167c584f25d6e61e622a285bb949c1602d464a38d3a2dff33462a9e70748"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
