name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff0c1aecd2d9fd662f8a4a107fceefe896b62087756825e98bc26100c9329c75"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
