name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c17e3b9637f118ba32847f4453367fb19257d5d681ec773602efce81e5ce7965"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
