name = "Vaulthalla"
author = "AlitaTeal"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa0199ace127aa101ce80a1a1ac06f52a1d83ae5c52bae92b910dce15e4d7a0b"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
