name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50f45411ae760be669006fd568eccbe205515bde34a84f637f441d98ce5dea8d"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
