name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04aa976b0d97c00de3dabe19e12976f69efd5f63eaa9130d478e7d3ba40665f6"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
