name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1eeeb67ba4e9f469d561f1646dd9d91a895b4b2b6f187eb7a642d12ae564e01c"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
