name = "Vaulthalla"
author = "AlitaTeal"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2c2af6f66e39bfbd155f7729f974e58b2ccae464af7d5f80a3d1e515b62c729"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
