name = "Vaulthalla"
author = "AlitaTeal"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "285658c4e8f8b26a7b570fdbcbd5f1f6d542ee66338754427fbe36b2ddffecb9"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
